import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "@/components/Wrapper";
import { Toaster } from "sonner";
import 'react-date-range/dist/styles.css'; // main css file
import 'react-date-range/dist/theme/default.css'; // theme css file


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nurul Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen ">
      <body className={inter.className}>
        <Toaster richColors={true} position="top-center" />
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
